"""empty message

Revision ID: fa49f5047ebb
Revises: 8141a452b4ab
Create Date: 2022-07-12 01:54:35.427900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa49f5047ebb'
down_revision = '8141a452b4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=240), nullable=True),
    sa.Column('photo', sa.TEXT(), nullable=True),
    sa.Column('dataset_file', sa.TEXT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=240), nullable=True),
    sa.Column('download_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
